exception: Consistency Error fix
- Fix Consistency Error Exception to be very explicit about what went
  wrong. The ConsistencyError Exception now outputs a message regarding
  the blockid, vaultid and the project id that caused the exception, and
  that message is logged.

- Prefix helper functions not intended for public consumption with '_'